// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6jLy5uiE7a0y7OCJBjDuI9WMZrue6uxQ',
    appId: '1:298171198138:android:769b3d501324cb2396f083',
    messagingSenderId: '298171198138',
    projectId: 'krishi-sakhi-farm',
    storageBucket: 'krishi-sakhi-farm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsh8UBQxi7FDQx-LKs4iAnFH2IALMlFKY',
    appId: '1:298171198138:ios:d159d814fe8e433f96f083',
    messagingSenderId: '298171198138',
    projectId: 'krishi-sakhi-farm',
    storageBucket: 'krishi-sakhi-farm.firebasestorage.app',
    iosBundleId: 'com.example.krishiSakhi',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAidG4whykcrF5nhw0i-QJXdVVCTdIm-2c',
    appId: '1:298171198138:web:b2e731af8f6c39fc96f083',
    messagingSenderId: '298171198138',
    projectId: 'krishi-sakhi-farm',
    authDomain: 'krishi-sakhi-farm.firebaseapp.com',
    storageBucket: 'krishi-sakhi-farm.firebasestorage.app',
    measurementId: 'G-FCW7L0HDNG',
  );

}